[jenkins]
jenkins-home

[all:vars]
; playbook vars
jenkins_home="/var/lib/jenkins"
backup_dir="/backup/jenkins_backup"
restore_dir="/restore/jenkins_backup"

; sftp backup
sftp_user="root"
sftp_host="192.168.8.146"
sftp_port="22"
remote_dir="/root/jenkins_backup"

sudo_user="jenkins"